sudo: required
language: generic
dist: trusty

matrix:
  include:
  - name: "Kinetic"
    env: ROS_DISTRO=kinetic BEFORE_SCRIPT="pip install --upgrade pip enum34 pyasn1-modules tensorflow==2.0 && hash -r pip"

install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config

script:
  - .ci_config/travis.sh
